# Generated by Django 2.0.1 on 2018-01-10 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('second_name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=1)),
                ('password', models.CharField(max_length=30)),
                ('password2', models.CharField(default='1234', max_length=30)),
                ('email', models.EmailField(default='home@mail.ru', max_length=45)),
                ('photo', models.FileField(blank=True, default='photo/default.png', upload_to='photo/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
    ]
